import os

from utils import File, Log

DIR_SRC = 'src'
SUB_DIRS = [
    os.path.join('nonview', 'base'),
    os.path.join('nonview', 'core'),
    os.path.join('nonview', 'constants'),
    os.path.join('view', 'atoms'),
    os.path.join('view', 'molecules'),
    os.path.join('view', 'organisms'),
    os.path.join('view', 'pages'),
]
log = Log('add indices')


def get_class_name_list(dir_sub: str) -> list[str]:
    class_name_list = []
    for file_name in os.listdir(dir_sub):
        if not file_name.endswith('.js'):
            continue
        if file_name == 'index.js':
            continue
        class_name = file_name[:-3]
        class_name_list.append(class_name)
    class_name_list.sort()
    return class_name_list


def main():
    assert os.path.exists(DIR_SRC)
    for sub_dir in SUB_DIRS:
        dir_sub = os.path.join(DIR_SRC, sub_dir)
        if not os.path.exists(dir_sub):
            continue

        class_name_list = get_class_name_list(dir_sub)

        lines = ['// Auto-generated by add_indices.py']
        for class_name in class_name_list:
            lines.append(f'import {class_name} from \'./{class_name}\'')
        lines.append('')
        lines.append('export {')
        for class_name in class_name_list:
            lines.append(f'  {class_name},')
        lines.append('}')
        lines.append('')

        file_path = os.path.join(dir_sub, 'index.js')
        File(file_path).write_lines(lines)
        log.info(f'Wrote {len(class_name_list)} classes to {file_path}')


if __name__ == '__main__':
    main()
