import os
import sys

from utils import File, Log, Time, TimeFormat

log = Log("javascript_version")


def format_message(commit_message: str) -> str:
    commit_message = commit_message.replace("Bug", "Bug🪳")
    commit_message = commit_message.replace("Fixed", "Fixed⚒️")
    commit_message = commit_message.replace("Minor", "Minor🤏")
    return commit_message


def main(commit_message: str):
    commit_message_formatted = format_message(commit_message)
    VERSION_FILE_PATH = os.path.join("src", "nonview", "cons", "VERSION.js")
    datetime_str = TimeFormat("%Y-%m-%d %H:%M:%S").stringify(Time.now())
    content = f"""
// Auto-generated by javascript_version.py
export const DATETIME_STR = '{datetime_str}';
export const VERSION_DATETIME = new Date(DATETIME_STR)
export const LAST_COMMIT_MESSAGE = '{commit_message_formatted}';
"""
    File(VERSION_FILE_PATH).write(content)
    log.info(f"Updated {VERSION_FILE_PATH} to {datetime_str}")


if __name__ == "__main__":
    main(sys.argv[1])
