import os

from utils import File, Log, Time, TimeFormat

log = Log("js/update_version")


def main():
    VERSION_FILE_PATH = os.path.join("src", "nonview", "cons", "VERSION.js")
    Q = 30 * 60
    time_rounded = Time(Q * int(Time.now().ut / Q))
    datetime_str = TimeFormat("%Y-%m-%d %H:%M").stringify(time_rounded)
    content = f"""
// Auto-generated by javascript_version.py
export const DATETIME_STR = '{datetime_str}';
export const VERSION_DATETIME = new Date(DATETIME_STR);

const VERSION = {{DATETIME_STR, VERSION_DATETIME}};
export default VERSION;

"""
    File(VERSION_FILE_PATH).write(content)
    log.info(f"Updated {VERSION_FILE_PATH} to {datetime_str}")


if __name__ == "__main__":
    main()
