import os

from utils import File as UtilsFile
from utils import Hash, Log, Time, TimeFormat

log = Log("js/update_version")


class File(UtilsFile):
    def has_changed(self, content):
        if not self.exists:
            return True
        existing_content = self.read()
        h_existing = Hash.md5(existing_content)
        h_new = Hash.md5(content)
        log.debug(f"Existing hash: {h_existing}")
        log.debug(f"New hash     : {h_new}")
        return h_existing != h_new

    def write_if_changed(self, content):
        if self.has_changed(content):
            self.write(content)
            return True
        return False


def main():
    VERSION_FILE_PATH = os.path.join("src", "nonview", "cons", "VERSION.js")
    Q = 30 * 60
    time_rounded = Time(Q * int(Time.now().ut / Q))
    datetime_str = TimeFormat("%Y-%m-%d %H:00").stringify(time_rounded)
    content = "\n".join(
        [
            "// Auto-generated by javascript_version.py",
            "",
            f'export const DATETIME_STR = "{datetime_str}";',
            "export const VERSION_DATETIME = new Date(DATETIME_STR);",
            "",
            "const VERSION = { DATETIME_STR, VERSION_DATETIME };",
            "export default VERSION;",
            "",
        ]
    )
    if File(VERSION_FILE_PATH).write_if_changed(content):
        log.info(f"Updated {VERSION_FILE_PATH} to {datetime_str}")


if __name__ == "__main__":
    main()
