import os

from utils import File, Log, Time, TimeFormat

log = Log('js/update_version')


def main():
    VERSION_FILE_PATH = os.path.join(
        'src', 'nonview', 'constants', 'VERSION.js'
    )
    datetime_str = TimeFormat('%Y-%m-%d %H:00').stringify(Time.now())
    content = f'''
// Auto-generated by javascript_version.py
export const DATETIME_STR = '{datetime_str}';
export const VERSION_DATETIME = new Date(DATETIME_STR);

const VERSION = {{DATETIME_STR, VERSION_DATETIME}};
export default VERSION;

'''
    File(VERSION_FILE_PATH).write(content)
    log.info(f'Updated {VERSION_FILE_PATH} to {datetime_str}')


if __name__ == '__main__':
    main()
